### ISSUE TITLE
match  results

### ISSUE THREAD

**Issue by jerryjifjsdbf** [Eunchan24/omniglue#1]
By cloning your project, you finally match two images, but there is this error in the middle
![demo_output](https://github.com/Eunchan24/omniglue/assets/130327433/b96d7902-c38b-4086-a708-0147d751615d)
![图片](https://github.com/Eunchan24/omniglue/assets/130327433/5cb77d6d-620a-4a10-85ec-be76cbff44ae)

**Comment by Eunchan24** [comment]
Hello. 
From the image above, it seems to be a problem with the Nvidia cuda compiler. :cry: 

Please let me know the OS, Cuda Version, GPU Name, pytorch, and tensorflow version, or write a reproducible code block and I think I can help you!

**Comment by jerryjifjsdbf** [comment]
> Hello. From the image above, it seems to be a problem with the Nvidia cuda compiler. 😢
> 
> Please let me know the OS, Cuda Version, GPU Name, pytorch, and tensorflow version, or write a reproducible code block and I think I can help you!

This is my conda list, which is installed by following the steps in readme：
![图片](https://github.com/Eunchan24/omniglue/assets/130327433/7381bd89-a541-4ec6-be82-e7510751320a)
![图片](https://github.com/Eunchan24/omniglue/assets/130327433/be786a4e-7a71-475e-af27-ddf8e2a5a0c6)

**Comment by Eunchan24** [comment]
Hello, I'm sorry for the late response. 
It seems to be a mismatch issue between the Nvidia driver and Cuda. 
Make sure your NVIDIA driver is up to date and compatible with the CUDA version!
